steps:
  # Build the container image using the Dockerfile that lives in docker/
  # Pass the *repository root* (.) as build-context so that COPY commands
  # inside the Dockerfile can access every file in the repo.
  - name: gcr.io/cloud-builders/docker
    id: Build container image
    args:
      - build
      - '.'
      - '-f'
      - 'docker/service.dockerfile'
      - '-t'
      - '${_IMAGE}'

# Cloud Run automatically sets the substitution variable _IMAGE to the fully
# qualified image name (gcr.io/PROJECT/...) when you deploy from source.
images:
  - '${_IMAGE}'
